apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: skyhype/print:GreenBeastoftheleaf
        ports:
        - containerPort: 8080
  strategy:
    blueGreen:
      activeService: myapp-service-blue
      previewService: myapp-service-green
      autoPromotionEnabled: false
