name: push to release branch

on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GIT_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ env.GH_TOKEN }}
            
      - name: update file in repo and commit
        run: |          
          git config --global user.email "email@gmail.com"
          git config --global user.name "user"
          random_string=$(openssl rand -base64 6)
          branch_name="branch-name-$random_string"
          git fetch
          git checkout -b $branch_name release/v1.0.1

          echo "Username: ${{ github.actor }}" >> new-file.txt
          
          git add .
          git commit -m "update-main-branch"
          git push --set-upstream origin $branch_name
          title="PR-Title"
          gh pr create -B release/v1.0.1 -H $branch_name --title $title --body 'Created by ${{ github.actor }}'
